### ISSUE TITLE
Feature request - Add fold/unfold

### ISSUE THREAD

**Issue by B0bbyD0llar** [chevere/var-dump#5]
Hello,

Nice would be the following functionality:

Fold and unfold objects, arrays in the UI to get better overview.

**Comment by rodber** [comment]
Thanks for your suggestion. The component in charge of render that is [chevere/var-dump](https://github.com/chevere/var-dump), I've moved the issue there.

**Comment by rodber** [comment]
Ref. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by rodber** [comment]
I've made significative progress in this request. Here's my hide/show thing:

<img width="783" alt="image" src="https://github.com/chevere/var-dump/assets/20590102/1e806f01-6b97-4b0c-87db-c95fa7d438cc">

This stuff is 100% HTML based, zero JS required. Also it docks on the left for better consistency.

https://github.com/chevere/var-dump/assets/20590102/595b6265-17ac-4574-a8e5-f04bd807bd0e

**Comment by B0bbyD0llar** [comment]
Looks great. Nice work so far.

**Comment by B0bbyD0llar** [comment]
Perhaps it would be a useful addition if the entries were automatically collapsed from the third level onwards. In my opinion, this would considerably simplify navigation in large amounts of data.

**Comment by rodber** [comment]
Sure the entries will be collapsed by default.

**Comment by rodber** [comment]
🎉 Folding is now included in the 1.1 branch.

![](https://raw.githubusercontent.com/chevere/var-dump/1.1/demo/demo-light.png)
